### ISSUE TITLE
他人のマイページ

### ISSUE THREAD

**Issue by kou7306** [kou7306/GeekLink_backend#15]
・まず、表示できるように
・いいねボタンを押して、Likeに追加できるように

**Comment by kappy713** [comment]
マッチングの確認は現在のコードで応用できそう
いいね部分はランダムマッチとは別で関数書く必要ありそう。

**Comment by kappy713** [comment]
いいね送る部分はできました
あとはフロントで自分が相手をいいねしているかの状態を管理すれば終了かな

**Comment by kappy713** [comment]
ん、状態管理が上手くいかない…
issueはクリアできたけど今のフロントの状態で出すのはよくない

**Comment by kappy713** [comment]
やっと実装できた…
いいねを取り消しする機能も欲しい気がするけど時間的に無理です。
前日に余裕があれば検討します。
