### ISSUE TITLE
グループ一覧の画面UIとバックエンド

### ISSUE THREAD

**Issue by kou7306** [kou7306/GeekLink_backend#31]
新たなグループだけの画面を作成

**Comment by kou7306** [comment]
新しい順で一旦

**Comment by kappy713** [comment]
カードで並べていく
1行に1グループ？

**Comment by kou7306** [comment]
それはカードごとの大きさのUIを見ながら臨機応変に。グリッドみたいな感じでも

**Comment by kou7306** [comment]
デザインはMUIを使うと簡単にできそう
https://mui.com/material-ui/react-card

**Comment by kou7306** [comment]
ヘッダーに飛べるように追加

**Comment by kappy713** [comment]
LINEのようなイメージいいかも。
グループ名(現時点ではないけどほしい)、グループのメンバー数、グループのメンバー名を一部表示？、(グループ概要)
クリックしたら/group/groupIDに飛べるように。
作る中で判断していく

**Comment by kappy713** [comment]
バックエンドは終了。フロントとAPIを繋ぐこともできたのであとはデザイン。
PS.眠くはないけど暑くて集中力が切れてきました(泣)

**Comment by kappy713** [comment]
素朴すぎるけど今の状態にグループ作成ボタンを加えればissueはクリアになるかな
